name: Deploy metro-boulot.photos Back

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-back.yml
      - app/back/**

jobs:
  deploy:
    name: Deploy metro-boulot.photos Back
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 167.71.143.97 >> ~/.ssh/known_hosts

      - name: Deploy metro-boulot.photos Back
        env:
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          TRIGGER_DEPLOY_KEY: ${{ secrets.TRIGGER_DEPLOY_KEY }}
          TRIGGER_API_KEY: ${{ secrets.TRIGGER_API_KEY }}
        run: |
          cd app/back
          bun install --frozen-lockfile
          bun run build
          bun run deploy
